/**
 * Generate the three shipped medal ghosts and write src/game/ghosts.ts.
 *
 *   npm run ghosts
 *
 * The laps are driven headlessly by src/game/sim/driver.ts with three skill
 * settings. Tune the settings against the paces printed, then commit the
 * generated file. Regenerate whenever the handling model or the track changes
 * — a ghost recorded on an old track drives through the new one's walls.
 */
import { writeFileSync } from 'node:fs'
import { DEFAULT_CAR } from '../src/game/sim/car'
import { encodeLap } from '../src/game/sim/recording'
import { buildTrack } from '../src/game/sim/track'
import { TRACK } from '../src/game/track-data'
import { driveRecordedLap, type Skill } from '../src/game/sim/driver'

const track = buildTrack(TRACK)

const MEDALS: { key: 'bronze' | 'silver' | 'gold'; skill: Skill }[] = [
  // Same line intent, slower reactions: the slower ghosts run wide and pay
  // off-track, which is how a slower human actually loses time here.
  { key: 'bronze', skill: { look: 160, every: 20, wander: 0, wanderPeriod: 2 } },
  { key: 'silver', skill: { look: 90, every: 10, wander: 0, wanderPeriod: 2 } },
  { key: 'gold', skill: { look: 90, every: 3, wander: 0, wanderPeriod: 2 } },
]

let out = `/**
 * Shipped medal ghosts — generated by scripts/record-ghosts.ts, do not edit.
 * Each is an encoded lap (see src/game/sim/recording.ts) plus its time.
 */
export type MedalKey = 'bronze' | 'silver' | 'gold'

export const MEDAL_GHOSTS: Record<MedalKey, { ms: number; lap: string }> = {
`
for (const m of MEDALS) {
  const r = driveRecordedLap(track, DEFAULT_CAR, m.skill)
  if (!r) throw new Error(`${m.key}: driver did not complete a valid lap`)
  const ms = Math.round((r.frames * 1000) / 60)
  const enc = encodeLap(r.lap)
  console.log(`${m.key.padEnd(6)} ${(ms / 1000).toFixed(3)}s  ${enc.length} bytes  ${r.lap.samples.length} samples`)
  out += `  ${m.key}: {\n    ms: ${ms},\n    lap: '${enc}',\n  },\n`
}
out += '}\n'
writeFileSync('src/game/ghosts.ts', out)
console.log('wrote src/game/ghosts.ts')
